import img from '../../../Assets/Images/profileimage.jpeg'

export const DummyPatientData=[
    {
        id: 1,
        profile: <img src={img} alt="Hospital Doctor Photograph" />,
        first_name: "Michael",
        last_name: "Brown",
        Sex: "Male",
        Age: 38,
        BloodGroup: "A",
        Mobile: +1234567890,
        City: "Peari River",
        Date: "7 / 9 / 2020",
        Time: "9: 34: 8",
        Options: "+ Alot",
    },
    {
        id: 2,
        profile: <img src={img} alt="Hospital Doctor Photograph" />,
        first_name: "Lucy",
        last_name: "White",
        Sex: "Female",
        Age: 30,
        BloodGroup: "B +",
        Mobile: +1234567890,
        City: "Tulsa",
        Date: "7 / 9 / 2020",
        Time: "9: 34: 8",
        Options: "Alotted",
    },
    {
        id: 3,
        profile: <img src={img} alt="Hospital Doctor Photograph" />,
        first_name: "Frank",
        last_name: "Hill",
        Sex: "Male",
        Age: 36,
        BloodGroup: "AB",
        Mobile: +1234567890,
        City: "BELLE CHASSE",
        Date: "7 / 9 / 2020",
        Time: "9: 34: 8",
        Options: "+ Alot",
    },
    {
        id: 4,
        profile: <img src={img} alt="Hospital Doctor Photograph" />,
        first_name: "Michael",
        last_name: "Glimpse",
        Sex: "Male",
        Age: 38,
        BloodGroup: "A",
        Mobile: +1234567890,
        City: "Peari River",
        Date: "7 / 9 / 2020",
        Time: "9: 34: 8",
        Options: "+ Alot",
    },
    {
        id: 5,
        profile: <img src={img} alt="Hospital Doctor Photograph" />,
        first_name: "Mike",
        last_name: "Capada",
        Sex: "Male",
        Age: 30,
        BloodGroup: "B +",
        Mobile: +1234567890,
        City: "Tulsa",
        Date: "7 / 9 / 2020",
        Time: "9: 34: 8",
        Options: "Alotted",
    },

];
